import { t } from '@/lib/i18n';

/**
 * A wallet's name in the reader's language.
 *
 * `WalletDto.name` is generated by the DATABASE, in English ("USD Wallet",
 * "Commission Wallet" — `schema.ts`, `wallets.name`), so printing it gave an
 * Arabic reader English on every statement, picker and balance cell. The name
 * is fully determined by the wallet's `kind` and `currency`, so it is composed
 * from the catalogue instead; the English keys repeat the database's wording,
 * so English screens read exactly as before.
 */
export function walletName(wallet: { kind?: string | null; currency: string }): string {
  if (wallet.kind === 'commission') return t('wallet.nameCommission');
  return t('wallet.nameMain', { currency: wallet.currency });
}
